import { User, Song, Playlist, Room, SongDedication, RadioStation, TopChart } from './types.js';

export const mockUsers: Record<string, User> = {
  'user-community-1': {
    id: 'user-community-1',
    name: 'Music Lover',
    handle: 'music_lover',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    status: 'online',
    streakDays: 1,
    totalListeningHours: 1.2,
    totalPlays: 12,
  },
  'user-community-2': {
    id: 'user-community-2',
    name: 'Friend',
    handle: 'friend',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    status: 'online',
    streakDays: 1,
    totalListeningHours: 2.5,
    totalPlays: 25,
  },
};

export const mockSongs: Song[] = [
  {
    id: 'song-apna-bana-le',
    title: 'Apna Bana Le',
    artist: 'Arijit Singh, Sachin-Jigar',
    album: 'Bhediya (Original Soundtrack)',
    durationSec: 261,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=melody-of-nature-110624.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&auto=format&fit=crop&q=80',
    genre: 'Bollywood',
    mood: 'Romantic',
    dominantColor: '#2b1b17', // Deep warm burgundy/amber
    youtubeId: 'UEvOsQBu1jY',
    lyrics: [
      { timeMs: 5000, text: 'Tu mera koi na hoke bhi kuch laage' },
      { timeMs: 15000, text: 'Kiya re jo bhi tune kiya re' },
      { timeMs: 25000, text: 'Apna bana le piya, apna bana le piya' },
      { timeMs: 38000, text: 'Dil ke nagar mein shehar tu basa le piya' },
      { timeMs: 52000, text: 'Chhute na chhute na aashiqui ye chhute na' },
    ],
    reactionTimeline: [
      { timestampSec: 25, type: '❤️', count: 42 },
      { timestampSec: 38, type: '😭', count: 28 },
      { timestampSec: 52, type: '🔥', count: 64 },
      { timestampSec: 110, type: '❤️', count: 89 },
    ],
  },
  {
    id: 'song-until-i-found-you',
    title: 'Until I Found You',
    artist: 'Stephen Sanchez',
    album: 'Easy on My Eyes',
    durationSec: 177,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=guitar-electro-sport-trailer-11559.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    genre: 'Indie',
    mood: 'Romantic',
    dominantColor: '#171d2b', // Deep midnight navy
    youtubeId: 'GxldQ9eX2wo',
    lyrics: [
      { timeMs: 4000, text: "Georgia, wrap me up in all your—" },
      { timeMs: 9000, text: "I want you in my arms" },
      { timeMs: 16000, text: "Oh, let me hold your heart" },
      { timeMs: 23000, text: "I would never fall in love until I found her" },
      { timeMs: 35000, text: "I said, I would never fall, unless it's you I fall into" },
    ],
    reactionTimeline: [
      { timestampSec: 23, type: '❤️', count: 112 },
      { timestampSec: 35, type: '😭', count: 95 },
      { timestampSec: 78, type: '❤️', count: 140 },
    ],
  },
  {
    id: 'song-damage-done',
    title: 'Damage Done',
    artist: 'Drake',
    album: 'Certified Lover Boy',
    durationSec: 178,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=tuesday-glitch-beat-1234.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    genre: 'Hip-Hop',
    mood: 'Chill',
    dominantColor: '#241a2e', // Deep atmospheric purple
    youtubeId: 'BddP6PYo2gs',
    lyrics: [
      { timeMs: 6000, text: "Late nights in the city, knowing what's done" },
      { timeMs: 14000, text: "Can't undo the damage, but we still run" },
      { timeMs: 28000, text: "Look at what we built, now it's cold as ice" },
      { timeMs: 42000, text: "Playing with the vibes, rolling with the dice" },
    ],
    reactionTimeline: [
      { timestampSec: 14, type: '🔥', count: 87 },
      { timestampSec: 28, type: '🔥', count: 120 },
      { timestampSec: 42, type: '❤️', count: 45 },
    ],
  },
  {
    id: 'song-starboy',
    title: 'Starboy',
    artist: 'The Weeknd, Daft Punk',
    album: 'Starboy',
    durationSec: 230,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2021/09/06/audio_8b05615d85.mp3?filename=electronic-future-beats-117997.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
    genre: 'R&B',
    mood: 'Energetic',
    dominantColor: '#2d1515', // Dark crimson atmosphere
    youtubeId: '34Na4j8AVgA',
    lyrics: [
      { timeMs: 8000, text: "I'm tryna put you in the worst mood, ah" },
      { timeMs: 15000, text: "P1 cleaner than your church shoes, ah" },
      { timeMs: 25000, text: "Look what you've done, I'm a motherfucking starboy" },
    ],
    reactionTimeline: [
      { timestampSec: 25, type: '🔥', count: 215 },
      { timestampSec: 65, type: '🔥', count: 180 },
    ],
  },
  {
    id: 'song-i-like-me-better',
    title: 'I Like Me Better',
    artist: 'Lauv',
    album: 'I met you when I was 18.',
    durationSec: 197,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/11/06/audio_924ebc69a7.mp3?filename=lofi-study-112191.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    genre: 'Pop',
    mood: 'Happy',
    dominantColor: '#172722', // Deep emerald dusk
    youtubeId: 'BcqxLCWn-CE',
    lyrics: [
      { timeMs: 5000, text: "To be young and in love in New York City" },
      { timeMs: 12000, text: "To not know who I am but still know that I'm good long as you're here with me" },
      { timeMs: 22000, text: "I like me better when I'm with you" },
    ],
    reactionTimeline: [
      { timestampSec: 22, type: '❤️', count: 98 },
      { timestampSec: 45, type: '❤️', count: 75 },
    ],
  },
  {
    id: 'song-midnight-city',
    title: 'Midnight Lo-Fi Echoes',
    artist: 'VibeRoom Originals',
    album: 'Night Drive Collective',
    durationSec: 165,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/16/audio_db6591201e.mp3?filename=lofi-chill-medium-version-112046.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80',
    genre: 'Lo-Fi',
    mood: 'Chill',
    dominantColor: '#1a192e', // Deep night indigo
    youtubeId: 'jfKfPfyJRdk',
    lyrics: [
      { timeMs: 10000, text: "(Gentle vinyl crackle and soothing chords)" },
      { timeMs: 30000, text: "(Distant city rain echoes)" },
    ],
    reactionTimeline: [
      { timestampSec: 30, type: '❤️', count: 82 },
      { timestampSec: 60, type: '🔥', count: 45 },
    ],
  },
];

export const mockPlaylists: Playlist[] = [
  {
    id: 'playlist-late-night-vibes',
    title: 'Late Night Vibes',
    stackedTitle: ['LATE', 'NIGHT', 'VIBES'],
    description: 'Slow down the world. Intimate vocals, quiet beats, and midnight reflections.',
    coverUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&auto=format&fit=crop&q=80',
    curatorName: 'Editorial VibeRoom',
    duration: '1h 42m',
    songCount: 24,
    isEditorial: true,
    songs: [mockSongs[0], mockSongs[1], mockSongs[4], mockSongs[5]],
  },
  {
    id: 'playlist-fomo',
    title: 'Fear Of Missing Out',
    stackedTitle: ['FEAR', 'OF', 'MISSING', 'OUT'],
    description: 'What everyone is listening to across the rooms right now.',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
    curatorName: 'VibeRoom Live',
    duration: '2h 10m',
    songCount: 38,
    isEditorial: true,
    songs: [mockSongs[3], mockSongs[2], mockSongs[0]],
  },
  {
    id: 'playlist-our-songs',
    title: 'Trending Favorites',
    stackedTitle: ['TRENDING', 'FAVORITES'],
    description: 'Community top rated tracks and viral sounds.',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    curatorName: 'Community Curated',
    duration: '54m',
    songCount: 14,
    isEditorial: false,
    songs: [mockSongs[0], mockSongs[1], mockSongs[4]],
  },
];

export const initialRooms: Room[] = [
  {
    id: 'room-late-night-bollywood',
    code: '8492',
    title: 'LATE NIGHT BOLLYWOOD',
    mode: 'public',
    controlMode: 'everyone',
    hostId: 'room-host',
    currentSong: mockSongs[0], // Apna Bana Le
    isPlaying: true,
    positionMs: 42000,
    serverTimestamp: Date.now(),
    members: [],
    queue: [mockSongs[0], mockSongs[1], mockSongs[4]],
    messages: [],
    reactions: [],
    listenerCount: 428,
  },
  {
    id: 'room-lofi-chill',
    code: '5120',
    title: 'LO-FI & CHILL',
    mode: 'public',
    controlMode: 'host_only',
    hostId: 'lofi-host',
    currentSong: mockSongs[5],
    isPlaying: true,
    positionMs: 15000,
    serverTimestamp: Date.now(),
    members: [],
    queue: [mockSongs[5], mockSongs[2]],
    messages: [],
    reactions: [],
    listenerCount: 234,
  },
];

export const mockDedications: SongDedication[] = [];

export const mockRadioStations: RadioStation[] = [
  {
    id: 'radio-bollywood-fm',
    name: 'Bollywood Hits FM',
    frequency: '98.3 FM',
    tagline: 'Non-stop Hindi romance & chartbusters',
    genre: 'Bollywood',
    coverUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80',
    currentSong: mockSongs[0],
    listenersCount: 4210,
    streamUrl: mockSongs[0].audioUrl,
  },
  {
    id: 'radio-midnight-lofi',
    name: 'Midnight Lo-Fi Lounge',
    frequency: '92.7 FM',
    tagline: 'Chill beats to study, relax and sleep to',
    genre: 'Lo-Fi',
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    currentSong: mockSongs[5],
    listenersCount: 1890,
    streamUrl: mockSongs[5].audioUrl,
  },
  {
    id: 'radio-global-hits',
    name: 'Global Viral Top 50',
    frequency: '104.2 FM',
    tagline: 'Worldwide pop, hip-hop and viral tracks',
    genre: 'Pop / Hip-Hop',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
    currentSong: mockSongs[3],
    listenersCount: 3120,
    streamUrl: mockSongs[3].audioUrl,
  },
  {
    id: 'radio-indie-acoustic',
    name: 'Acoustic Sunset',
    frequency: '101.5 FM',
    tagline: 'Raw vocals, intimate guitars and indie vibes',
    genre: 'Indie',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    currentSong: mockSongs[1],
    listenersCount: 940,
    streamUrl: mockSongs[1].audioUrl,
  },
];

export const mockTopCharts: TopChart[] = [
  {
    id: 'chart-india-top10',
    title: 'Top 10 India',
    subtitle: 'The most played songs in India right now',
    country: 'IN',
    coverUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80',
    songs: [mockSongs[0], mockSongs[1], mockSongs[4], mockSongs[2]],
  },
  {
    id: 'chart-global-viral',
    title: 'Global Viral 50',
    subtitle: 'Worldwide tracks catching fire on VibeRoom',
    country: 'GL',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
    songs: [mockSongs[3], mockSongs[2], mockSongs[1], mockSongs[5]],
  },
];

