import { Track, createAlbumArtSvg } from '../mockData.js';

export interface ContextualSoundscape {
  id: string;
  name: string;
  emoji: string;
  tagline: string;
  description: string;
  mood: string;
  tempo: string;
  energy: number; // 0-100
  accentColor: string;
  secondaryColor: string;
  gradient: string;
  targetKeywords: string[];
  tracks: Track[];
}

export const CONTEXTUAL_SOUNDSCAPES: ContextualSoundscape[] = [
  {
    id: '2am-drive',
    name: '2 AM Drive',
    emoji: '🌙',
    tagline: 'Dark, atmospheric, smooth and immersive late-night music',
    description: 'Analog synthesizers, dark R&B, and smooth nighttime driving rhythms for empty highways.',
    mood: 'Dark & Atmospheric',
    tempo: 'Mid-tempo (95–118 BPM)',
    energy: 65,
    accentColor: '#8B5CF6',
    secondaryColor: '#FF3D81',
    gradient: 'from-[#1F1435] via-[#8B5CF6] to-[#0A0A0C]',
    targetKeywords: ['2 am', 'drive', 'night drive', 'after hours', 'dark', 'midnight', 'late night'],
    tracks: [
      {
        id: 'ctx-2am-1',
        title: 'After Hours',
        artist: 'The Weeknd',
        album: 'After Hours',
        duration: 361,
        accentColor: '#FF3D81',
        secondaryColor: '#8B5CF6',
        artworkSvg: createAlbumArtSvg('AFTER HOURS', '#FF3D81', '#8B5CF6', 'orb'),
        genre: 'Darkwave Synth R&B',
        bpm: 109,
        energy: 68,
        plays: 894000000,
        likes: 12400000,
        youtubeId: 'ygTZZpVHNpc',
        lyrics: [
          { time: 0, text: '♪ Thought I almost died in my dream again ♪' },
          { time: 24, text: 'Fightin\' for my life, I couldn\'t breathe again' },
          { time: 52, text: 'Flashin\' lights make me blind, inside this car tonight' },
          { time: 88, text: 'Where are you now when I need you most?' },
        ],
      },
      {
        id: 'ctx-2am-2',
        title: 'Nights',
        artist: 'Frank Ocean',
        album: 'Blonde',
        duration: 307,
        accentColor: '#8B5CF6',
        secondaryColor: '#22D3EE',
        artworkSvg: createAlbumArtSvg('NIGHTS', '#8B5CF6', '#22D3EE', 'waves'),
        genre: 'Atmospheric R&B',
        bpm: 90,
        energy: 60,
        plays: 720000000,
        likes: 9800000,
        youtubeId: 'r4l9bFqgMaQ',
        lyrics: [
          { time: 0, text: '♪ Round your city, round the clock ♪' },
          { time: 28, text: 'Everybody needs you, no, you can\'t make everybody happy' },
          { time: 80, text: 'Stayin\' out late, driving down the boulevard' },
          { time: 130, text: 'Every night hits every night...' },
        ],
      },
      {
        id: 'ctx-2am-3',
        title: 'The Hills',
        artist: 'The Weeknd',
        album: 'Beauty Behind the Madness',
        duration: 242,
        accentColor: '#FF6B5A',
        secondaryColor: '#1F1F25',
        artworkSvg: createAlbumArtSvg('THE HILLS', '#FF6B5A', '#8B5CF6', 'mesh'),
        genre: 'Dark Trap R&B',
        bpm: 113,
        energy: 72,
        plays: 1820000000,
        likes: 18400000,
        youtubeId: 'yzTuBuRdAyA',
        lyrics: [
          { time: 0, text: '♪ Your man on the road, he doin\' promo ♪' },
          { time: 18, text: 'You said, "Keep our business on the low-low"' },
          { time: 42, text: 'I only call you when it\'s half past five' },
          { time: 64, text: 'The only time that I\'d be by your side' },
        ],
      },
      {
        id: 'ctx-2am-4',
        title: 'Do I Wanna Know?',
        artist: 'Arctic Monkeys',
        album: 'AM',
        duration: 272,
        accentColor: '#22D3EE',
        secondaryColor: '#8B5CF6',
        artworkSvg: createAlbumArtSvg('AM', '#22D3EE', '#121215', 'vinyl'),
        genre: 'Moody Indie Rock',
        bpm: 85,
        energy: 64,
        plays: 1950000000,
        likes: 21000000,
        youtubeId: 'bpOSxM0zyN8',
        lyrics: [
          { time: 0, text: '♪ Have you got colour in your cheeks? ♪' },
          { time: 18, text: 'Do you ever get that fear that you can\'t shift the type?' },
          { time: 45, text: 'Crawlin\' back to you, late night in the cold' },
          { time: 70, text: 'Do I wanna know if this feeling flows both ways?' },
        ],
      },
    ],
  },
  {
    id: 'morning',
    name: 'Morning Sunlight',
    emoji: '☀️',
    tagline: 'Warm, uplifting, light and positive songs',
    description: 'Gentle acoustic warmth, breezy melodies, and vibrant positivity to start your day.',
    mood: 'Uplifting & Positive',
    tempo: 'Gentle Bounce (100–120 BPM)',
    energy: 70,
    accentColor: '#FF6B5A',
    secondaryColor: '#B6F23A',
    gradient: 'from-[#FF6B5A]/20 via-[#B6F23A]/15 to-[#0A0A0C]',
    targetKeywords: ['morning', 'sunlight', 'sunrise', 'wake up', 'positive', 'golden', 'uplifting'],
    tracks: [
      {
        id: 'ctx-morn-1',
        title: 'Golden',
        artist: 'Harry Styles',
        album: 'Fine Line',
        duration: 208,
        accentColor: '#FF6B5A',
        secondaryColor: '#B6F23A',
        artworkSvg: createAlbumArtSvg('GOLDEN', '#FF6B5A', '#B6F23A', 'orb'),
        genre: 'Indie Pop',
        bpm: 140,
        energy: 84,
        plays: 1200000000,
        likes: 14000000,
        youtubeId: 'P3cffdsEXXw',
        lyrics: [
          { time: 0, text: '♪ Golden, golden, golden as I open my eyes ♪' },
          { time: 20, text: 'Holding, focus, hoping take me into the light' },
          { time: 45, text: 'I know that you\'re scared because I\'m so open' },
          { time: 70, text: 'You\'re so golden...' },
        ],
      },
      {
        id: 'ctx-morn-2',
        title: 'Sunday Best',
        artist: 'Surfaces',
        album: 'Where the Light Is',
        duration: 158,
        accentColor: '#B6F23A',
        secondaryColor: '#22D3EE',
        artworkSvg: createAlbumArtSvg('SUNDAY BEST', '#B6F23A', '#22D3EE', 'mesh'),
        genre: 'Feel-Good Pop',
        bpm: 112,
        energy: 65,
        plays: 950000000,
        likes: 11000000,
        youtubeId: '_83K3Qe44MT',
        lyrics: [
          { time: 0, text: '♪ Feeling good, like I should ♪' },
          { time: 16, text: 'Went and took a walk around the neighborhood' },
          { time: 38, text: 'Feeling blessed, never stressed' },
          { time: 54, text: 'Got that sunshine on my Sunday best' },
        ],
      },
      {
        id: 'ctx-morn-3',
        title: 'Here Comes The Sun',
        artist: 'The Beatles',
        album: 'Abbey Road',
        duration: 185,
        accentColor: '#FF3D81',
        secondaryColor: '#FF6B5A',
        artworkSvg: createAlbumArtSvg('ABBEY ROAD', '#FF3D81', '#FF6B5A', 'geometric'),
        genre: 'Classic Acoustic Rock',
        bpm: 129,
        energy: 55,
        plays: 1400000000,
        likes: 16500000,
        youtubeId: 'KQetemT1sWc',
        lyrics: [
          { time: 0, text: '♪ Here comes the sun, doo-doo-doo-doo ♪' },
          { time: 20, text: 'Here comes the sun, and I say: It\'s alright' },
          { time: 42, text: 'Little darling, it\'s been a long cold lonely winter' },
          { time: 70, text: 'Little darling, it feels like years since it\'s been here' },
        ],
      },
      {
        id: 'ctx-morn-4',
        title: 'Put Your Records On',
        artist: 'Ritt Momney / Corinne Bailey Rae',
        album: 'Heretic',
        duration: 210,
        accentColor: '#22D3EE',
        secondaryColor: '#B6F23A',
        artworkSvg: createAlbumArtSvg('RECORDS ON', '#22D3EE', '#B6F23A', 'waves'),
        genre: 'Soulful Indie Pop',
        bpm: 96,
        energy: 62,
        plays: 680000000,
        likes: 7500000,
        youtubeId: '2m89e9V8pZg',
        lyrics: [
          { time: 0, text: '♪ Three little birds sat on my window ♪' },
          { time: 22, text: 'And they told me I don\'t need to worry' },
          { time: 48, text: 'Girl, put your records on, tell me your favourite song' },
          { time: 72, text: 'You go ahead, let your hair down' },
        ],
      },
    ],
  },
  {
    id: 'workout',
    name: 'High-Tempo Workout',
    emoji: '⚡',
    tagline: 'Energetic, motivating, high-tempo anthems',
    description: 'Fast BPM, heavy basslines, and relentless adrenaline drops to shatter your workout limits.',
    mood: 'High Energy & Adrenaline',
    tempo: 'Fast (128–145 BPM)',
    energy: 95,
    accentColor: '#B6F23A',
    secondaryColor: '#FF3D81',
    gradient: 'from-[#B6F23A]/20 via-[#FF3D81]/15 to-[#0A0A0C]',
    targetKeywords: ['workout', 'gym', 'energy', 'hype', 'cardio', 'pump', 'high energy'],
    tracks: [
      {
        id: 'ctx-work-1',
        title: 'Stronger',
        artist: 'Kanye West',
        album: 'Graduation',
        duration: 312,
        accentColor: '#B6F23A',
        secondaryColor: '#8B5CF6',
        artworkSvg: createAlbumArtSvg('STRONGER', '#B6F23A', '#8B5CF6', 'geometric'),
        genre: 'Electro Hip-Hop',
        bpm: 123,
        energy: 92,
        plays: 1650000000,
        likes: 17800000,
        youtubeId: 'PsO6ZnUZI0g',
        lyrics: [
          { time: 0, text: '♪ Work it, make it, do it, makes us ♪' },
          { time: 14, text: 'Harder, better, faster, stronger' },
          { time: 38, text: 'That that don\'t kill me can only make me stronger' },
          { time: 65, text: 'I need you to hurry up now, \'cause I can\'t wait much longer' },
        ],
      },
      {
        id: 'ctx-work-2',
        title: 'Can\'t Hold Us',
        artist: 'Macklemore & Ryan Lewis',
        album: 'The Heist',
        duration: 258,
        accentColor: '#FF6B5A',
        secondaryColor: '#B6F23A',
        artworkSvg: createAlbumArtSvg('THE HEIST', '#FF6B5A', '#B6F23A', 'mesh'),
        genre: 'Hype Hip-Hop',
        bpm: 146,
        energy: 96,
        plays: 1980000000,
        likes: 21500000,
        youtubeId: '2zNSgS772P8',
        lyrics: [
          { time: 0, text: '♪ Return of the Mack, get \'em, what it is, what it does ♪' },
          { time: 24, text: 'This is the moment, tonight is the night' },
          { time: 48, text: 'Can we go back, this is the moment, tonight is the night' },
          { time: 70, text: 'Like the ceiling can\'t hold us!' },
        ],
      },
      {
        id: 'ctx-work-3',
        title: 'Till I Collapse',
        artist: 'Eminem ft. Nate Dogg',
        album: 'The Eminem Show',
        duration: 297,
        accentColor: '#FF3D81',
        secondaryColor: '#FF6B5A',
        artworkSvg: createAlbumArtSvg('TILL I COLLAPSE', '#FF3D81', '#FF6B5A', 'vinyl'),
        genre: 'Hardcore Rap',
        bpm: 171,
        energy: 94,
        plays: 1890000000,
        likes: 19200000,
        youtubeId: 'ytQ5CYE1VZw',
        lyrics: [
          { time: 0, text: '♪ \'Til the roof comes off, \'til the lights go out ♪' },
          { time: 18, text: '\'Til my legs give out, can\'t shut my mouth' },
          { time: 42, text: '\'Til the smoke clears out, am I high? Perhaps' },
          { time: 64, text: 'I\'ma rip this till I collapse!' },
        ],
      },
      {
        id: 'ctx-work-4',
        title: 'Power',
        artist: 'Kanye West',
        album: 'My Beautiful Dark Twisted Fantasy',
        duration: 292,
        accentColor: '#8B5CF6',
        secondaryColor: '#B6F23A',
        artworkSvg: createAlbumArtSvg('POWER', '#8B5CF6', '#B6F23A', 'orb'),
        genre: 'Stadium Hip-Hop',
        bpm: 154,
        energy: 95,
        plays: 1250000000,
        likes: 13900000,
        youtubeId: 'L53gjP-Tt2w',
        lyrics: [
          { time: 0, text: '♪ I\'m living in the 21st century ♪' },
          { time: 16, text: 'Doing something mean to it' },
          { time: 40, text: 'No one man should have all that power' },
          { time: 62, text: 'The clock\'s ticking, I just count the hours' },
        ],
      },
    ],
  },
  {
    id: 'study',
    name: 'Deep Study & Focus',
    emoji: '☕',
    tagline: 'Calm, low-distraction, mellow and instrumental textures',
    description: 'Zero distraction, soothing vinyl warmth, and ambient frequencies designed for deep work.',
    mood: 'Calm & Flow State',
    tempo: 'Slow (70–85 BPM)',
    energy: 25,
    accentColor: '#22D3EE',
    secondaryColor: '#8B5CF6',
    gradient: 'from-[#22D3EE]/15 via-[#8B5CF6]/15 to-[#0A0A0C]',
    targetKeywords: ['study', 'focus', 'chill', 'coding', 'lofi', 'flow state', 'calm'],
    tracks: [
      {
        id: 'ctx-std-1',
        title: 'Weightless',
        artist: 'Marconi Union',
        album: 'Weightless (Ambient)',
        duration: 480,
        accentColor: '#22D3EE',
        secondaryColor: '#8B5CF6',
        artworkSvg: createAlbumArtSvg('WEIGHTLESS', '#22D3EE', '#8B5CF6', 'waves'),
        genre: 'Ambient Calm',
        bpm: 60,
        energy: 15,
        plays: 450000000,
        likes: 6200000,
        youtubeId: 'UfcAVejslrU',
        lyrics: [
          { time: 0, text: '♪ Deep harmonic frequency ♪' },
          { time: 60, text: 'Zero distraction, pure focus' },
          { time: 180, text: 'Drifting into theta state...' },
        ],
      },
      {
        id: 'ctx-std-2',
        title: 'Snowman',
        artist: 'WYS',
        album: '1 Am. Study Session',
        duration: 174,
        accentColor: '#8B5CF6',
        secondaryColor: '#22D3EE',
        artworkSvg: createAlbumArtSvg('SNOWMAN', '#8B5CF6', '#22D3EE', 'mesh'),
        genre: 'Lo-Fi Hip Hop',
        bpm: 76,
        energy: 30,
        plays: 380000000,
        likes: 5400000,
        youtubeId: 'Ea8p-V5fH9g',
        lyrics: [
          { time: 0, text: '♪ Vinyl crackle and soft electric piano ♪' },
          { time: 40, text: 'Warm rain falling outside the window' },
          { time: 90, text: 'Steady rhythm, steady mind' },
        ],
      },
      {
        id: 'ctx-std-3',
        title: 'Affection',
        artist: 'Jinsang',
        album: 'Life',
        duration: 160,
        accentColor: '#FF6B5A',
        secondaryColor: '#22D3EE',
        artworkSvg: createAlbumArtSvg('AFFECTION', '#FF6B5A', '#22D3EE', 'orb'),
        genre: 'Lo-Fi Chill Beats',
        bpm: 82,
        energy: 32,
        plays: 310000000,
        likes: 4800000,
        youtubeId: 'f3k_wT50QzM',
        lyrics: [
          { time: 0, text: '♪ Mellow jazz guitar chords ♪' },
          { time: 35, text: 'Dusty snares and calming low-end groove' },
        ],
      },
      {
        id: 'ctx-std-4',
        title: 'Coffee Breath',
        artist: 'Sofia Mills',
        album: 'Red',
        duration: 165,
        accentColor: '#B6F23A',
        secondaryColor: '#22D3EE',
        artworkSvg: createAlbumArtSvg('COFFEE BREATH', '#B6F23A', '#22D3EE', 'geometric'),
        genre: 'Acoustic Lo-Fi',
        bpm: 78,
        energy: 28,
        plays: 290000000,
        likes: 3900000,
        youtubeId: 'k543Kk4J0_U',
        lyrics: [
          { time: 0, text: '♪ Soft acoustic fingerpicking ♪' },
          { time: 25, text: 'Quiet room with coffee aroma' },
        ],
      },
    ],
  },
  {
    id: 'rainy-evening',
    name: 'Rainy Evening',
    emoji: '🌧️',
    tagline: 'Emotional, atmospheric and mellow songs',
    description: 'Raw acoustic melancholy, intimate whispering vocals, and gentle rain outside the glass.',
    mood: 'Emotional & Mellow',
    tempo: 'Slow to Mid-tempo (75–92 BPM)',
    energy: 38,
    accentColor: '#22D3EE',
    secondaryColor: '#1F1F25',
    gradient: 'from-[#142335] via-[#22D3EE]/20 to-[#0A0A0C]',
    targetKeywords: ['rain', 'rainy', 'evening', 'melancholy', 'mellow', 'skinny love', 'cardigan'],
    tracks: [
      {
        id: 'ctx-rain-1',
        title: 'Skinny Love',
        artist: 'Bon Iver',
        album: 'For Emma, Forever Ago',
        duration: 238,
        accentColor: '#22D3EE',
        secondaryColor: '#8B5CF6',
        artworkSvg: createAlbumArtSvg('BON IVER', '#22D3EE', '#8B5CF6', 'waves'),
        genre: 'Indie Folk',
        bpm: 77,
        energy: 36,
        plays: 680000000,
        likes: 7200000,
        youtubeId: 'ssdgFoHAhm8',
        lyrics: [
          { time: 0, text: '♪ Come on skinny love, just last the year ♪' },
          { time: 22, text: 'Pour a little salt we were never here' },
          { time: 54, text: 'My, my, my, my, my, my, my, my' },
        ],
      },
      {
        id: 'ctx-rain-2',
        title: 'cardigan',
        artist: 'Taylor Swift',
        album: 'folklore',
        duration: 239,
        accentColor: '#8B5CF6',
        secondaryColor: '#22D3EE',
        artworkSvg: createAlbumArtSvg('FOLKLORE', '#8B5CF6', '#22D3EE', 'mesh'),
        genre: 'Chamber Pop',
        bpm: 130,
        energy: 48,
        plays: 910000000,
        likes: 12500000,
        youtubeId: 'K-a8s8OLBSE',
        lyrics: [
          { time: 0, text: '♪ Vintage tee, brand new phone ♪' },
          { time: 24, text: 'High heels on cobblestones' },
          { time: 48, text: 'And when I felt like I was an old cardigan under someone\'s bed' },
          { time: 70, text: 'You put me on and said I was your favourite' },
        ],
      },
      {
        id: 'ctx-rain-3',
        title: 'Roslyn',
        artist: 'Bon Iver & St. Vincent',
        album: 'The Twilight Saga',
        duration: 289,
        accentColor: '#FF6B5A',
        secondaryColor: '#22D3EE',
        artworkSvg: createAlbumArtSvg('ROSLYN', '#FF6B5A', '#22D3EE', 'orb'),
        genre: 'Atmospheric Folk',
        bpm: 82,
        energy: 32,
        plays: 490000000,
        likes: 6100000,
        youtubeId: 's79_m1gO9k8',
        lyrics: [
          { time: 0, text: '♪ Up with your turret, aren\'t we just terrified? ♪' },
          { time: 30, text: 'Sea and the rock below, cocked to the undertow' },
        ],
      },
      {
        id: 'ctx-rain-4',
        title: 'Mystery of Love',
        artist: 'Sufjan Stevens',
        album: 'Call Me by Your Name',
        duration: 248,
        accentColor: '#B6F23A',
        secondaryColor: '#FF6B5A',
        artworkSvg: createAlbumArtSvg('MYSTERY OF LOVE', '#B6F23A', '#FF6B5A', 'geometric'),
        genre: 'Acoustic Chamber Folk',
        bpm: 88,
        energy: 35,
        plays: 740000000,
        likes: 8900000,
        youtubeId: '4WTt69YO2Yo',
        lyrics: [
          { time: 0, text: '♪ Oh, to see without my eyes ♪' },
          { time: 24, text: 'The first time that you kissed me' },
          { time: 54, text: 'Lord, I thought that I was too hurt to ever love again' },
        ],
      },
    ],
  },
  {
    id: 'party',
    name: 'Nightclub & Dance',
    emoji: '🪩',
    tagline: 'Energetic, driving and danceable anthems',
    description: 'Slap basslines, euphoric four-on-the-floor drops, and peak-hour party energy.',
    mood: 'Danceable & Euphoric',
    tempo: 'Four-on-the-floor (124–128 BPM)',
    energy: 94,
    accentColor: '#FF3D81',
    secondaryColor: '#8B5CF6',
    gradient: 'from-[#351428] via-[#FF3D81] to-[#0A0A0C]',
    targetKeywords: ['party', 'club', 'dance', 'disco', 'levitating', 'one kiss', 'nightclub'],
    tracks: [
      {
        id: 'ctx-pty-1',
        title: 'One Kiss',
        artist: 'Calvin Harris & Dua Lipa',
        album: 'One Kiss',
        duration: 214,
        accentColor: '#FF3D81',
        secondaryColor: '#8B5CF6',
        artworkSvg: createAlbumArtSvg('ONE KISS', '#FF3D81', '#8B5CF6', 'orb'),
        genre: 'Club Dance House',
        bpm: 124,
        energy: 95,
        plays: 1980000000,
        likes: 19500000,
        youtubeId: 'DkeiKbqa02g',
        lyrics: [
          { time: 0, text: '♪ One kiss is all it takes ♪' },
          { time: 14, text: 'Fallin\' in love with me, possibilities' },
          { time: 38, text: 'I look like all you need' },
          { time: 55, text: 'Let me take the night, I love real' },
        ],
      },
      {
        id: 'ctx-pty-2',
        title: 'Levitating',
        artist: 'Dua Lipa',
        album: 'Future Nostalgia',
        duration: 203,
        accentColor: '#8B5CF6',
        secondaryColor: '#22D3EE',
        artworkSvg: createAlbumArtSvg('LEVITATING', '#8B5CF6', '#22D3EE', 'waves'),
        genre: 'Disco Pop',
        bpm: 103,
        energy: 92,
        plays: 2100000000,
        likes: 22000000,
        youtubeId: 'TUVcZfQe-Kw',
        lyrics: [
          { time: 0, text: '♪ If you wanna run away with me, I know a galaxy ♪' },
          { time: 20, text: 'And I can take you for a ride' },
          { time: 42, text: 'I got you, moonlight, you\'re my starlight' },
          { time: 62, text: 'I need you all night, come on dance with me' },
        ],
      },
      {
        id: 'ctx-pty-3',
        title: 'Don\'t Start Now',
        artist: 'Dua Lipa',
        album: 'Future Nostalgia',
        duration: 183,
        accentColor: '#B6F23A',
        secondaryColor: '#FF3D81',
        artworkSvg: createAlbumArtSvg('DONT START NOW', '#B6F23A', '#FF3D81', 'mesh'),
        genre: 'Nu-Disco Funk',
        bpm: 124,
        energy: 91,
        plays: 2400000000,
        likes: 24500000,
        youtubeId: 'oygrmJFKYZY',
        lyrics: [
          { time: 0, text: '♪ If you don\'t wanna see me dancing with somebody ♪' },
          { time: 24, text: 'Don\'t show up, don\'t come out' },
          { time: 45, text: 'Don\'t start caring about me now' },
        ],
      },
      {
        id: 'ctx-pty-4',
        title: 'Yeah!',
        artist: 'Usher ft. Lil Jon, Ludacris',
        album: 'Confessions',
        duration: 250,
        accentColor: '#FF6B5A',
        secondaryColor: '#B6F23A',
        artworkSvg: createAlbumArtSvg('CONFESSIONS', '#FF6B5A', '#B6F23A', 'vinyl'),
        genre: 'Crunk Dance R&B',
        bpm: 105,
        energy: 93,
        plays: 1750000000,
        likes: 18000000,
        youtubeId: 'GxBSyx85FW8',
        lyrics: [
          { time: 0, text: '♪ Peace up, A-Town down! ♪' },
          { time: 20, text: 'Yeah, yeah, yeah, yeah!' },
          { time: 45, text: 'In the club with the homies, trying to get a lil\' V-I' },
        ],
      },
    ],
  },
  {
    id: 'heartbreak',
    name: 'Heartbreak & Healing',
    emoji: '💔',
    tagline: 'Emotional, vulnerable and melancholic ballads',
    description: 'Stripped-back piano chords, poignant heartbreak, and cathartic emotional crescendos.',
    mood: 'Melancholic & Cathartic',
    tempo: 'Slow (65–85 BPM)',
    energy: 45,
    accentColor: '#22D3EE',
    secondaryColor: '#FF3D81',
    gradient: 'from-[#142335] via-[#FF3D81]/20 to-[#0A0A0C]',
    targetKeywords: ['heartbreak', 'sad', 'crying', 'broken', 'someone like you', 'drivers license', 'melancholy'],
    tracks: [
      {
        id: 'ctx-hbrk-1',
        title: 'Someone Like You',
        artist: 'Adele',
        album: '21',
        duration: 285,
        accentColor: '#22D3EE',
        secondaryColor: '#8B5CF6',
        artworkSvg: createAlbumArtSvg('ADELE 21', '#22D3EE', '#8B5CF6', 'orb'),
        genre: 'Piano Ballad',
        bpm: 67,
        energy: 35,
        plays: 1980000000,
        likes: 21000000,
        youtubeId: 'hLQl3WQQoQ0',
        lyrics: [
          { time: 0, text: '♪ I heard that you\'re settled down ♪' },
          { time: 20, text: 'That you found a girl and you\'re married now' },
          { time: 54, text: 'Never mind, I\'ll find someone like you' },
          { time: 82, text: 'I wish nothing but the best for you too' },
        ],
      },
      {
        id: 'ctx-hbrk-2',
        title: 'drivers license',
        artist: 'Olivia Rodrigo',
        album: 'SOUR',
        duration: 242,
        accentColor: '#FF3D81',
        secondaryColor: '#8B5CF6',
        artworkSvg: createAlbumArtSvg('SOUR', '#FF3D81', '#8B5CF6', 'mesh'),
        genre: 'Bedroom Pop Ballad',
        bpm: 144,
        energy: 55,
        plays: 2200000000,
        likes: 23500000,
        youtubeId: 'ZmDBbnmKpqQ',
        lyrics: [
          { time: 0, text: '♪ I got my driver\'s license last week ♪' },
          { time: 22, text: 'Just like we always talked about' },
          { time: 50, text: '\'Cause you were so excited for me' },
          { time: 76, text: '\'Cause how could I ever love someone else?' },
        ],
      },
      {
        id: 'ctx-hbrk-3',
        title: 'Glimpse of Us',
        artist: 'Joji',
        album: 'SMITHEREENS',
        duration: 233,
        accentColor: '#8B5CF6',
        secondaryColor: '#22D3EE',
        artworkSvg: createAlbumArtSvg('JOJI', '#8B5CF6', '#22D3EE', 'waves'),
        genre: 'Lo-Fi Melancholy',
        bpm: 170,
        energy: 38,
        plays: 1350000000,
        likes: 15200000,
        youtubeId: 'FvOpPeKSf_4',
        lyrics: [
          { time: 0, text: '♪ She\'d take the world off my shoulders ♪' },
          { time: 25, text: '\'Cause sometimes I look in her eyes and that\'s where I find a glimpse of us' },
        ],
      },
      {
        id: 'ctx-hbrk-4',
        title: 'traitor',
        artist: 'Olivia Rodrigo',
        album: 'SOUR',
        duration: 229,
        accentColor: '#FF6B5A',
        secondaryColor: '#FF3D81',
        artworkSvg: createAlbumArtSvg('TRAITOR', '#FF6B5A', '#FF3D81', 'geometric'),
        genre: 'Acoustic Heartbreak',
        bpm: 100,
        energy: 48,
        plays: 1600000000,
        likes: 16800000,
        youtubeId: '6tsgkx51UA0',
        lyrics: [
          { time: 0, text: '♪ Brown guilty eyes and little white lies ♪' },
          { time: 24, text: 'You betrayed me, and I know that you\'ll never feel sorry' },
        ],
      },
    ],
  },
  {
    id: 'romantic',
    name: 'Romantic Intimacy',
    emoji: '🌹',
    tagline: 'Intimate, warm, emotional and soulful love songs',
    description: 'Vintage 50s doo-wop warmth, candlelit R&B, and timeless acoustic devotion.',
    mood: 'Intimate & Devoted',
    tempo: 'Waltz & Slow Sway (75–96 BPM)',
    energy: 52,
    accentColor: '#FF3D81',
    secondaryColor: '#FF6B5A',
    gradient: 'from-[#351420] via-[#FF3D81]/25 to-[#0A0A0C]',
    targetKeywords: ['romantic', 'love', 'intimate', 'until i found you', 'die for you', 'perfect', 'date night'],
    tracks: [
      {
        id: 'ctx-rom-1',
        title: 'Until I Found You',
        artist: 'Stephen Sanchez',
        album: 'Easy on My Eyes',
        duration: 177,
        accentColor: '#FF3D81',
        secondaryColor: '#FF6B5A',
        artworkSvg: createAlbumArtSvg('UNTIL I FOUND YOU', '#FF3D81', '#FF6B5A', 'orb'),
        genre: '50s Doo-Wop Romance',
        bpm: 101,
        energy: 56,
        plays: 1850000000,
        likes: 19800000,
        youtubeId: 'GxldQ9eX2wo',
        lyrics: [
          { time: 0, text: '♪ Georgia, wrap me up in all your... ♪' },
          { time: 18, text: 'I would never fall in love until I found her' },
          { time: 42, text: 'I said, "I would never fall unless it\'s you I fall into"' },
          { time: 68, text: 'I was lost within the darkness, but then I found her' },
        ],
      },
      {
        id: 'ctx-rom-2',
        title: 'Die For You',
        artist: 'The Weeknd',
        album: 'Starboy',
        duration: 260,
        accentColor: '#8B5CF6',
        secondaryColor: '#FF3D81',
        artworkSvg: createAlbumArtSvg('DIE FOR YOU', '#8B5CF6', '#FF3D81', 'mesh'),
        genre: 'Passionate Modern R&B',
        bpm: 134,
        energy: 60,
        plays: 2300000000,
        likes: 24000000,
        youtubeId: 'QLCpqdqeoII',
        lyrics: [
          { time: 0, text: '♪ I\'m findin\' ways to articulate the feeling I\'m going through ♪' },
          { time: 24, text: 'I quit telling \'em that I don\'t want you' },
          { time: 48, text: '\'Cause baby, I would die for you' },
          { time: 70, text: 'Yes, I would die for you, baby' },
        ],
      },
      {
        id: 'ctx-rom-3',
        title: 'Perfect',
        artist: 'Ed Sheeran',
        album: '÷ (Divide)',
        duration: 263,
        accentColor: '#FF6B5A',
        secondaryColor: '#22D3EE',
        artworkSvg: createAlbumArtSvg('PERFECT', '#FF6B5A', '#22D3EE', 'geometric'),
        genre: 'Acoustic Love Ballad',
        bpm: 95,
        energy: 45,
        plays: 2800000000,
        likes: 27500000,
        youtubeId: '2Vv-BfVoq4g',
        lyrics: [
          { time: 0, text: '♪ I found a love for me ♪' },
          { time: 18, text: 'Darling, just dive right in and follow my lead' },
          { time: 42, text: '\'Cause darling, you look perfect tonight' },
        ],
      },
      {
        id: 'ctx-rom-4',
        title: 'Lover',
        artist: 'Taylor Swift',
        album: 'Lover',
        duration: 221,
        accentColor: '#FF3D81',
        secondaryColor: '#B6F23A',
        artworkSvg: createAlbumArtSvg('LOVER', '#FF3D81', '#B6F23A', 'waves'),
        genre: 'Retro Waltz Romance',
        bpm: 68,
        energy: 54,
        plays: 1400000000,
        likes: 15600000,
        youtubeId: '-BjZmE2gtdo',
        lyrics: [
          { time: 0, text: '♪ We could leave the Christmas lights up \'til January ♪' },
          { time: 24, text: 'And this is our place, we make the rules' },
          { time: 48, text: 'Can I go where you go? Can we always be this close forever and ever?' },
        ],
      },
    ],
  },
  {
    id: 'road-trip',
    name: 'Open Road Trip',
    emoji: '🚗',
    tagline: 'Energetic, nostalgic and sing-along anthems',
    description: 'Windows down, warm wind, loud choruses, and unforgettable highway nostalgia.',
    mood: 'Nostalgic & High Spirits',
    tempo: 'Driving Beat (120–148 BPM)',
    energy: 88,
    accentColor: '#B6F23A',
    secondaryColor: '#FF6B5A',
    gradient: 'from-[#1E2E18] via-[#B6F23A]/25 to-[#0A0A0C]',
    targetKeywords: ['road trip', 'drive', 'highway', 'windows down', 'riptide', 'mr brightside', 'sing-along'],
    tracks: [
      {
        id: 'ctx-rd-1',
        title: 'Riptide',
        artist: 'Vance Joy',
        album: 'Dream Your Life Away',
        duration: 204,
        accentColor: '#B6F23A',
        secondaryColor: '#FF6B5A',
        artworkSvg: createAlbumArtSvg('RIPTIDE', '#B6F23A', '#FF6B5A', 'orb'),
        genre: 'Indie Folk Anthem',
        bpm: 102,
        energy: 73,
        plays: 2450000000,
        likes: 24000000,
        youtubeId: 'uJ_1HMAGb4k',
        lyrics: [
          { time: 0, text: '♪ I was scared of dentists and the dark ♪' },
          { time: 18, text: 'I was scared of pretty girls and starting conversations' },
          { time: 42, text: 'Lady, running down to the riptide' },
          { time: 64, text: 'Taken away to the dark side' },
        ],
      },
      {
        id: 'ctx-rd-2',
        title: 'Tongue Tied',
        artist: 'GROUPLOVE',
        album: 'Never Trust a Happy Song',
        duration: 218,
        accentColor: '#22D3EE',
        secondaryColor: '#B6F23A',
        artworkSvg: createAlbumArtSvg('GROUPLOVE', '#22D3EE', '#B6F23A', 'mesh'),
        genre: 'Indie Pop Energy',
        bpm: 113,
        energy: 90,
        plays: 1200000000,
        likes: 13500000,
        youtubeId: '1x1wjGKHoz0',
        lyrics: [
          { time: 0, text: '♪ Take me to your best friend\'s house ♪' },
          { time: 18, text: 'I loved you then and I love you now' },
          { time: 40, text: 'Don\'t leave me tongue-tied!' },
        ],
      },
      {
        id: 'ctx-rd-3',
        title: 'Shut Up and Dance',
        artist: 'WALK THE MOON',
        album: 'TALKING IS HARD',
        duration: 199,
        accentColor: '#FF3D81',
        secondaryColor: '#22D3EE',
        artworkSvg: createAlbumArtSvg('SHUT UP DANCE', '#FF3D81', '#22D3EE', 'waves'),
        genre: 'Upbeat 80s Indie Pop',
        bpm: 128,
        energy: 88,
        plays: 1950000000,
        likes: 19800000,
        youtubeId: '6JCLY0RmxwQ',
        lyrics: [
          { time: 0, text: '♪ Oh, don\'t you dare look back ♪' },
          { time: 18, text: 'Just keep your eyes on me' },
          { time: 40, text: 'She said, "Shut up and dance with me!"' },
        ],
      },
      {
        id: 'ctx-rd-4',
        title: 'Mr. Brightside',
        artist: 'The Killers',
        album: 'Hot Fuss',
        duration: 222,
        accentColor: '#8B5CF6',
        secondaryColor: '#FF6B5A',
        artworkSvg: createAlbumArtSvg('HOT FUSS', '#8B5CF6', '#FF6B5A', 'geometric'),
        genre: 'Alternative Rock Anthem',
        bpm: 148,
        energy: 94,
        plays: 2300000000,
        likes: 24200000,
        youtubeId: 'gGdGFtwCNBE',
        lyrics: [
          { time: 0, text: '♪ Coming out of my cage and I\'ve been doing just fine ♪' },
          { time: 18, text: 'Gotta gotta be down because I want it all' },
          { time: 45, text: 'Now I\'m falling asleep and she\'s calling a cab' },
          { time: 72, text: '\'Cause I\'m Mr. Brightside!' },
        ],
      },
    ],
  },
];

// Helper to look up a soundscape by keyword
export function findContextualSoundscape(query: string): ContextualSoundscape | null {
  const clean = query.trim().toLowerCase();
  if (!clean) return null;

  for (const soundscape of CONTEXTUAL_SOUNDSCAPES) {
    if (
      soundscape.id === clean ||
      soundscape.name.toLowerCase().includes(clean) ||
      clean.includes(soundscape.name.toLowerCase()) ||
      soundscape.targetKeywords.some((kw) => clean.includes(kw))
    ) {
      return soundscape;
    }
  }
  return null;
}

